[package]
name = "specht2"
version = "0.1.0"
authors = ["zhuhaow <zhuhaow@gmail.com>"]
edition = "2018"

[dependencies]
freighter = { path = "../" }
tokio = "^0.1"
trust-dns-resolver = "^0.12"
future-utils = "^0.12"
futures = "^0.1"

[lib]
crate-type = ["lib", "staticlib"]

[[bin]]
name = "specht"
